### ISSUE TITLE
sword renaming

### ISSUE THREAD

**Issue by ChosenMark** [JongWasTaken/Baubley-Heart-Canisters-Fabric#2]
when renaming sword using the name My Beautiful Eyes it does not change look like it does on forge version

**Comment by JongWasTaken** [comment]
Hello,
Thank you for opening an issue!  
This has now been re-implemented in the newest version (1.0.2).  
It is already available on Modrinth. The CurseForge release is still waiting for approval, which should finish in the next few hours.
