### ISSUE TITLE
mod issue

### ISSUE THREAD

**Issue by ChosenMark** [JongWasTaken/Baubley-Heart-Canisters-Fabric#3]
Mod 'Baubley Heart Canisters' (bhc) 1.0.2 requires version 3.7.2 of mod 'Accessories Trinkets Compat Layer' (tclayer), but only the wrong versions are present: 3.8.1-alpha.11/3.8.0!

**Comment by ChosenMark** [comment]
please make work with latest version of Accessories Trinkets Compat Layer' (tclayer)

**Comment by JongWasTaken** [comment]
Should be fixed in 1.0.4, which I just uploaded to [Modrinth](https://modrinth.com/mod/bhc-fabric/version/uI35czA6) and CurseForge(still pending verification).  
Please tell me if the issue is resolved!

**Comment by ChosenMark** [comment]
please dont there mod is very broken still please revert

**Comment by ChosenMark** [comment]
> Should be fixed in 1.0.4, which I just uploaded to [Modrinth](https://modrinth.com/mod/bhc-fabric/version/uI35czA6) and CurseForge(still pending verification). Please tell me if the issue is resolved!

dont do it there mod is very broken please remove the need for that mod

**Comment by JongWasTaken** [comment]
There is no need to revert, I just relaxed the required trinkets version, which shouldn't cause any issues whatsoever.

**Comment by JongWasTaken** [comment]
Also trinkets is recommended anyways so whatever.
